let suggestions = [
    "Channel",
    "CodingLab",
    "CodingNepal",
    "YouTube",
    "YouTuber",
    "YouTube Channel",
    "Blogger",
    "Bollywood",
    "Vlogger",
    "Vechiles",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to become Freelancer",
    "How to become Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
    "Instagram",
    "Twitter",
    "Instagram",
    "Telegram",
    "Python",
    "Javascript",
    "React",
    "Vue Js",
    "Next Js",
    "Angular",
    "Full Stack Developer",
    "Front End Developer",
    "Back End Developer",
    "Ui Ux",
    "Git",
    "Github",
    "Django",
    "Node Js",
    "Project",
    "How to apload Project in Linkdin",
    "Resume",
];
